// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: demo/v1/cart.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuInfo     []*CreateCartRequest_SkuInfo `protobuf:"bytes,1,rep,name=sku_info,json=skuInfo,proto3" json:"sku_info,omitempty"`
	PromotionId int32                        `protobuf:"varint,2,opt,name=promotion_id,json=promotionId,proto3" json:"promotion_id,omitempty"`
	SourceId    string                       `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceUrl   string                       `protobuf:"bytes,4,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
}

func (x *CreateCartRequest) Reset() {
	*x = CreateCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartRequest) ProtoMessage() {}

func (x *CreateCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartRequest.ProtoReflect.Descriptor instead.
func (*CreateCartRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCartRequest) GetSkuInfo() []*CreateCartRequest_SkuInfo {
	if x != nil {
		return x.SkuInfo
	}
	return nil
}

func (x *CreateCartRequest) GetPromotionId() int32 {
	if x != nil {
		return x.PromotionId
	}
	return 0
}

func (x *CreateCartRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *CreateCartRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

type CreateCartReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateCartReply) Reset() {
	*x = CreateCartReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCartReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartReply) ProtoMessage() {}

func (x *CreateCartReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartReply.ProtoReflect.Descriptor instead.
func (*CreateCartReply) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{1}
}

type QuantityUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartId     int32  `protobuf:"varint,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	GoodsNum   int32  `protobuf:"varint,2,opt,name=goods_num,json=goodsNum,proto3" json:"goods_num,omitempty"`
	SkuUnionid string `protobuf:"bytes,3,opt,name=sku_unionid,json=skuUnionid,proto3" json:"sku_unionid,omitempty"`
}

func (x *QuantityUpdateRequest) Reset() {
	*x = QuantityUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuantityUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantityUpdateRequest) ProtoMessage() {}

func (x *QuantityUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantityUpdateRequest.ProtoReflect.Descriptor instead.
func (*QuantityUpdateRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{2}
}

func (x *QuantityUpdateRequest) GetCartId() int32 {
	if x != nil {
		return x.CartId
	}
	return 0
}

func (x *QuantityUpdateRequest) GetGoodsNum() int32 {
	if x != nil {
		return x.GoodsNum
	}
	return 0
}

func (x *QuantityUpdateRequest) GetSkuUnionid() string {
	if x != nil {
		return x.SkuUnionid
	}
	return ""
}

type QuantityUpdateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QuantityUpdateReply) Reset() {
	*x = QuantityUpdateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuantityUpdateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuantityUpdateReply) ProtoMessage() {}

func (x *QuantityUpdateReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuantityUpdateReply.ProtoReflect.Descriptor instead.
func (*QuantityUpdateReply) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{3}
}

type DeleteCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartIds []int32 `protobuf:"varint,1,rep,packed,name=cart_ids,json=cartIds,proto3" json:"cart_ids,omitempty"`
}

func (x *DeleteCartRequest) Reset() {
	*x = DeleteCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartRequest) ProtoMessage() {}

func (x *DeleteCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartRequest.ProtoReflect.Descriptor instead.
func (*DeleteCartRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCartRequest) GetCartIds() []int32 {
	if x != nil {
		return x.CartIds
	}
	return nil
}

type DeleteCartReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartListInfo *CartListInfo `protobuf:"bytes,1,opt,name=cart_list_info,proto3" json:"cart_list_info,omitempty"`
}

func (x *DeleteCartReply) Reset() {
	*x = DeleteCartReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCartReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartReply) ProtoMessage() {}

func (x *DeleteCartReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartReply.ProtoReflect.Descriptor instead.
func (*DeleteCartReply) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCartReply) GetCartListInfo() *CartListInfo {
	if x != nil {
		return x.CartListInfo
	}
	return nil
}

type GetCartQuantityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCartQuantityRequest) Reset() {
	*x = GetCartQuantityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCartQuantityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartQuantityRequest) ProtoMessage() {}

func (x *GetCartQuantityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartQuantityRequest.ProtoReflect.Descriptor instead.
func (*GetCartQuantityRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{6}
}

type GetCartQuantitytReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartListNum int32 `protobuf:"varint,1,opt,name=cart_list_num,proto3" json:"cart_list_num,omitempty"`
}

func (x *GetCartQuantitytReply) Reset() {
	*x = GetCartQuantitytReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCartQuantitytReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartQuantitytReply) ProtoMessage() {}

func (x *GetCartQuantitytReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartQuantitytReply.ProtoReflect.Descriptor instead.
func (*GetCartQuantitytReply) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{7}
}

func (x *GetCartQuantitytReply) GetCartListNum() int32 {
	if x != nil {
		return x.CartListNum
	}
	return 0
}

type ListCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCartRequest) Reset() {
	*x = ListCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCartRequest) ProtoMessage() {}

func (x *ListCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCartRequest.ProtoReflect.Descriptor instead.
func (*ListCartRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{8}
}

type ListCartReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartListInfo *CartListInfo `protobuf:"bytes,1,opt,name=cart_list_info,proto3" json:"cart_list_info,omitempty"`
}

func (x *ListCartReply) Reset() {
	*x = ListCartReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCartReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCartReply) ProtoMessage() {}

func (x *ListCartReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCartReply.ProtoReflect.Descriptor instead.
func (*ListCartReply) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{9}
}

func (x *ListCartReply) GetCartListInfo() *CartListInfo {
	if x != nil {
		return x.CartListInfo
	}
	return nil
}

type CheckedCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartIds []int32 `protobuf:"varint,1,rep,packed,name=cart_ids,json=cartIds,proto3" json:"cart_ids,omitempty"`
	Checked int32   `protobuf:"varint,2,opt,name=checked,proto3" json:"checked,omitempty"`
}

func (x *CheckedCartRequest) Reset() {
	*x = CheckedCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckedCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckedCartRequest) ProtoMessage() {}

func (x *CheckedCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckedCartRequest.ProtoReflect.Descriptor instead.
func (*CheckedCartRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{10}
}

func (x *CheckedCartRequest) GetCartIds() []int32 {
	if x != nil {
		return x.CartIds
	}
	return nil
}

func (x *CheckedCartRequest) GetChecked() int32 {
	if x != nil {
		return x.Checked
	}
	return 0
}

type CheckedCartReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartListInfo *CartListInfo `protobuf:"bytes,3,opt,name=cart_list_info,proto3" json:"cart_list_info,omitempty"`
}

func (x *CheckedCartReply) Reset() {
	*x = CheckedCartReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckedCartReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckedCartReply) ProtoMessage() {}

func (x *CheckedCartReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckedCartReply.ProtoReflect.Descriptor instead.
func (*CheckedCartReply) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{11}
}

func (x *CheckedCartReply) GetCartListInfo() *CartListInfo {
	if x != nil {
		return x.CartListInfo
	}
	return nil
}

//购物车列表共用字段
type CartListInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CartListInfo) Reset() {
	*x = CartListInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CartListInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartListInfo) ProtoMessage() {}

func (x *CartListInfo) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartListInfo.ProtoReflect.Descriptor instead.
func (*CartListInfo) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{12}
}

type ChangeCartSkuInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuUnionid string `protobuf:"bytes,1,opt,name=spu_unionid,json=spuUnionid,proto3" json:"spu_unionid,omitempty"`
	CartId     int32  `protobuf:"varint,2,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
}

func (x *ChangeCartSkuInfoRequest) Reset() {
	*x = ChangeCartSkuInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeCartSkuInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeCartSkuInfoRequest) ProtoMessage() {}

func (x *ChangeCartSkuInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeCartSkuInfoRequest.ProtoReflect.Descriptor instead.
func (*ChangeCartSkuInfoRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{13}
}

func (x *ChangeCartSkuInfoRequest) GetSpuUnionid() string {
	if x != nil {
		return x.SpuUnionid
	}
	return ""
}

func (x *ChangeCartSkuInfoRequest) GetCartId() int32 {
	if x != nil {
		return x.CartId
	}
	return 0
}

type ChangeCartSkuInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeCartSkuInfoReply) Reset() {
	*x = ChangeCartSkuInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeCartSkuInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeCartSkuInfoReply) ProtoMessage() {}

func (x *ChangeCartSkuInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeCartSkuInfoReply.ProtoReflect.Descriptor instead.
func (*ChangeCartSkuInfoReply) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{14}
}

type ChangeCartSkuRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeCartSkuRequest) Reset() {
	*x = ChangeCartSkuRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeCartSkuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeCartSkuRequest) ProtoMessage() {}

func (x *ChangeCartSkuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeCartSkuRequest.ProtoReflect.Descriptor instead.
func (*ChangeCartSkuRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{15}
}

type ChangeCartSkuReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartListInfo *CartListInfo `protobuf:"bytes,1,opt,name=cart_list_info,proto3" json:"cart_list_info,omitempty"`
}

func (x *ChangeCartSkuReply) Reset() {
	*x = ChangeCartSkuReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeCartSkuReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeCartSkuReply) ProtoMessage() {}

func (x *ChangeCartSkuReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeCartSkuReply.ProtoReflect.Descriptor instead.
func (*ChangeCartSkuReply) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{16}
}

func (x *ChangeCartSkuReply) GetCartListInfo() *CartListInfo {
	if x != nil {
		return x.CartListInfo
	}
	return nil
}

type CreateCartRequest_SkuInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuUnionid string `protobuf:"bytes,1,opt,name=sku_unionid,json=skuUnionid,proto3" json:"sku_unionid,omitempty"`
	GoodsNum   int32  `protobuf:"varint,2,opt,name=goods_num,json=goodsNum,proto3" json:"goods_num,omitempty"`
}

func (x *CreateCartRequest_SkuInfo) Reset() {
	*x = CreateCartRequest_SkuInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_cart_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCartRequest_SkuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartRequest_SkuInfo) ProtoMessage() {}

func (x *CreateCartRequest_SkuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_cart_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartRequest_SkuInfo.ProtoReflect.Descriptor instead.
func (*CreateCartRequest_SkuInfo) Descriptor() ([]byte, []int) {
	return file_demo_v1_cart_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateCartRequest_SkuInfo) GetSkuUnionid() string {
	if x != nil {
		return x.SkuUnionid
	}
	return ""
}

func (x *CreateCartRequest_SkuInfo) GetGoodsNum() int32 {
	if x != nil {
		return x.GoodsNum
	}
	return 0
}

var File_demo_v1_cart_proto protoreflect.FileDescriptor

var file_demo_v1_cart_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x9a, 0x02, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x42, 0x0a, 0x08, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53,
	0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x92, 0x01, 0x02, 0x08, 0x01,
	0x52, 0x07, 0x73, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x0c, 0x70, 0x72, 0x6f,
	0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x1a, 0x02, 0x28, 0x00, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x72,
	0x6c, 0x1a, 0x59, 0x0a, 0x07, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x28, 0x0a, 0x0b,
	0x73, 0x6b, 0x75, 0x5f, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x0d, 0x52, 0x0a, 0x73, 0x6b, 0x75, 0x55,
	0x6e, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x09, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f,
	0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x1a, 0x02,
	0x20, 0x00, 0x52, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x75, 0x6d, 0x22, 0x11, 0x0a, 0x0f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x8b, 0x01, 0x0a, 0x15, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x07, 0x63, 0x61, 0x72,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x1a,
	0x02, 0x20, 0x00, 0x52, 0x06, 0x63, 0x61, 0x72, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x09, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x09,
	0xfa, 0x42, 0x06, 0x1a, 0x04, 0x18, 0x63, 0x20, 0x00, 0x52, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x4e, 0x75, 0x6d, 0x12, 0x28, 0x0a, 0x0b, 0x73, 0x6b, 0x75, 0x5f, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10,
	0x0d, 0x52, 0x0a, 0x73, 0x6b, 0x75, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x22, 0x15, 0x0a,
	0x13, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x38, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x08, 0x63, 0x61, 0x72,
	0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x42, 0x08, 0xfa, 0x42, 0x05,
	0x92, 0x01, 0x02, 0x08, 0x01, 0x52, 0x07, 0x63, 0x61, 0x72, 0x74, 0x49, 0x64, 0x73, 0x22, 0x4b,
	0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x38, 0x0a, 0x0e, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x63, 0x61, 0x72,
	0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x18, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3d, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74,
	0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x24,
	0x0a, 0x0d, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x5f, 0x6e, 0x75, 0x6d, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x49, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x38, 0x0a, 0x0e, 0x63, 0x61, 0x72, 0x74,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0e, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x22, 0x5e, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x43, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x74,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x92,
	0x01, 0x02, 0x08, 0x01, 0x52, 0x07, 0x63, 0x61, 0x72, 0x74, 0x49, 0x64, 0x73, 0x12, 0x23, 0x0a,
	0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x09,
	0xfa, 0x42, 0x06, 0x1a, 0x04, 0x30, 0x00, 0x30, 0x01, 0x52, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x65, 0x64, 0x22, 0x4c, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x43, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x38, 0x0a, 0x0e, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0e, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x66, 0x0a, 0x18, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x61, 0x72, 0x74, 0x53, 0x6b,
	0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0b,
	0x73, 0x70, 0x75, 0x5f, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x0d, 0x52, 0x0a, 0x73, 0x70, 0x75, 0x55,
	0x6e, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x1a, 0x02, 0x20, 0x00,
	0x52, 0x06, 0x63, 0x61, 0x72, 0x74, 0x49, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x43, 0x61, 0x72, 0x74, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x61, 0x72, 0x74,
	0x53, 0x6b, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4e, 0x0a, 0x12, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x43, 0x61, 0x72, 0x74, 0x53, 0x6b, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x38, 0x0a, 0x0e, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61,
	0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x63, 0x61, 0x72, 0x74,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x32, 0xc5, 0x06, 0x0a, 0x04, 0x43,
	0x61, 0x72, 0x74, 0x12, 0x59, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72,
	0x74, 0x12, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1f, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x19, 0x3a, 0x01, 0x2a, 0x22, 0x14, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x2f, 0x61, 0x64, 0x64, 0x12, 0x75,
	0x0a, 0x12, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x61, 0x72, 0x74, 0x12, 0x19, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x25,
	0x3a, 0x01, 0x2a, 0x22, 0x20, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32,
	0x2f, 0x63, 0x61, 0x72, 0x74, 0x2f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2d, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x5c, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x61, 0x72, 0x74, 0x12, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x3a, 0x01, 0x2a, 0x22, 0x17, 0x2f, 0x73, 0x68, 0x6f,
	0x70, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x2f, 0x72, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x12, 0x6e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x51, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x72, 0x74, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x74, 0x51,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x24, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x3a, 0x01, 0x2a, 0x22, 0x19, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x2f, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x54, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x74, 0x12,
	0x13, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x3a,
	0x01, 0x2a, 0x22, 0x15, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f,
	0x63, 0x61, 0x72, 0x74, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x60, 0x0a, 0x0b, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x65, 0x64, 0x43, 0x61, 0x72, 0x74, 0x12, 0x16, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x65, 0x64, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x43, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x3a, 0x01,
	0x2a, 0x22, 0x18, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x63,
	0x61, 0x72, 0x74, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x7a, 0x0a, 0x11, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x61, 0x72, 0x74, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1c, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x61, 0x72, 0x74,
	0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x61, 0x72, 0x74, 0x53, 0x6b,
	0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2b, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x25, 0x3a, 0x01, 0x2a, 0x22, 0x20, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x32, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2d, 0x73,
	0x6b, 0x75, 0x2d, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x69, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x43, 0x61, 0x72, 0x74, 0x53, 0x6b, 0x75, 0x12, 0x18, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x43, 0x61, 0x72, 0x74, 0x53, 0x6b, 0x75, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x61,
	0x72, 0x74, 0x53, 0x6b, 0x75, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x26, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x20, 0x3a, 0x01, 0x2a, 0x22, 0x1b, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x32, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2d, 0x73,
	0x6b, 0x75, 0x42, 0x10, 0x5a, 0x0e, 0x62, 0x65, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x61, 0x70,
	0x69, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_demo_v1_cart_proto_rawDescOnce sync.Once
	file_demo_v1_cart_proto_rawDescData = file_demo_v1_cart_proto_rawDesc
)

func file_demo_v1_cart_proto_rawDescGZIP() []byte {
	file_demo_v1_cart_proto_rawDescOnce.Do(func() {
		file_demo_v1_cart_proto_rawDescData = protoimpl.X.CompressGZIP(file_demo_v1_cart_proto_rawDescData)
	})
	return file_demo_v1_cart_proto_rawDescData
}

var file_demo_v1_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_demo_v1_cart_proto_goTypes = []interface{}{
	(*CreateCartRequest)(nil),         // 0: v1.CreateCartRequest
	(*CreateCartReply)(nil),           // 1: v1.CreateCartReply
	(*QuantityUpdateRequest)(nil),     // 2: v1.QuantityUpdateRequest
	(*QuantityUpdateReply)(nil),       // 3: v1.QuantityUpdateReply
	(*DeleteCartRequest)(nil),         // 4: v1.DeleteCartRequest
	(*DeleteCartReply)(nil),           // 5: v1.DeleteCartReply
	(*GetCartQuantityRequest)(nil),    // 6: v1.GetCartQuantityRequest
	(*GetCartQuantitytReply)(nil),     // 7: v1.GetCartQuantitytReply
	(*ListCartRequest)(nil),           // 8: v1.ListCartRequest
	(*ListCartReply)(nil),             // 9: v1.ListCartReply
	(*CheckedCartRequest)(nil),        // 10: v1.CheckedCartRequest
	(*CheckedCartReply)(nil),          // 11: v1.CheckedCartReply
	(*CartListInfo)(nil),              // 12: v1.CartListInfo
	(*ChangeCartSkuInfoRequest)(nil),  // 13: v1.ChangeCartSkuInfoRequest
	(*ChangeCartSkuInfoReply)(nil),    // 14: v1.ChangeCartSkuInfoReply
	(*ChangeCartSkuRequest)(nil),      // 15: v1.ChangeCartSkuRequest
	(*ChangeCartSkuReply)(nil),        // 16: v1.ChangeCartSkuReply
	(*CreateCartRequest_SkuInfo)(nil), // 17: v1.CreateCartRequest.SkuInfo
}
var file_demo_v1_cart_proto_depIdxs = []int32{
	17, // 0: v1.CreateCartRequest.sku_info:type_name -> v1.CreateCartRequest.SkuInfo
	12, // 1: v1.DeleteCartReply.cart_list_info:type_name -> v1.CartListInfo
	12, // 2: v1.ListCartReply.cart_list_info:type_name -> v1.CartListInfo
	12, // 3: v1.CheckedCartReply.cart_list_info:type_name -> v1.CartListInfo
	12, // 4: v1.ChangeCartSkuReply.cart_list_info:type_name -> v1.CartListInfo
	0,  // 5: v1.Cart.CreateCart:input_type -> v1.CreateCartRequest
	2,  // 6: v1.Cart.QuantityUpdateCart:input_type -> v1.QuantityUpdateRequest
	4,  // 7: v1.Cart.DeleteCart:input_type -> v1.DeleteCartRequest
	6,  // 8: v1.Cart.GetCartQuantity:input_type -> v1.GetCartQuantityRequest
	8,  // 9: v1.Cart.ListCart:input_type -> v1.ListCartRequest
	10, // 10: v1.Cart.CheckedCart:input_type -> v1.CheckedCartRequest
	13, // 11: v1.Cart.ChangeCartSkuInfo:input_type -> v1.ChangeCartSkuInfoRequest
	15, // 12: v1.Cart.ChangeCartSku:input_type -> v1.ChangeCartSkuRequest
	1,  // 13: v1.Cart.CreateCart:output_type -> v1.CreateCartReply
	3,  // 14: v1.Cart.QuantityUpdateCart:output_type -> v1.QuantityUpdateReply
	5,  // 15: v1.Cart.DeleteCart:output_type -> v1.DeleteCartReply
	7,  // 16: v1.Cart.GetCartQuantity:output_type -> v1.GetCartQuantitytReply
	9,  // 17: v1.Cart.ListCart:output_type -> v1.ListCartReply
	11, // 18: v1.Cart.CheckedCart:output_type -> v1.CheckedCartReply
	14, // 19: v1.Cart.ChangeCartSkuInfo:output_type -> v1.ChangeCartSkuInfoReply
	16, // 20: v1.Cart.ChangeCartSku:output_type -> v1.ChangeCartSkuReply
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_demo_v1_cart_proto_init() }
func file_demo_v1_cart_proto_init() {
	if File_demo_v1_cart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_demo_v1_cart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCartReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuantityUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuantityUpdateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCartReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCartQuantityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCartQuantitytReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCartReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckedCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckedCartReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CartListInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeCartSkuInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeCartSkuInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeCartSkuRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeCartSkuReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_cart_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCartRequest_SkuInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_demo_v1_cart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo_v1_cart_proto_goTypes,
		DependencyIndexes: file_demo_v1_cart_proto_depIdxs,
		MessageInfos:      file_demo_v1_cart_proto_msgTypes,
	}.Build()
	File_demo_v1_cart_proto = out.File
	file_demo_v1_cart_proto_rawDesc = nil
	file_demo_v1_cart_proto_goTypes = nil
	file_demo_v1_cart_proto_depIdxs = nil
}
