// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: demo/v1/goods.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//SpuList
type SpuListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *SpuListRequest) Reset() {
	*x = SpuListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpuListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpuListRequest) ProtoMessage() {}

func (x *SpuListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpuListRequest.ProtoReflect.Descriptor instead.
func (*SpuListRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{0}
}

func (x *SpuListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SpuListRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SpuListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpuListReply) Reset() {
	*x = SpuListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpuListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpuListReply) ProtoMessage() {}

func (x *SpuListReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpuListReply.ProtoReflect.Descriptor instead.
func (*SpuListReply) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{1}
}

//SpuInfo
type SpuInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuUuid string `protobuf:"bytes,1,opt,name=spu_uuid,proto3" json:"spu_uuid,omitempty"`
	Extend  int32  `protobuf:"varint,2,opt,name=extend,proto3" json:"extend,omitempty"`
}

func (x *SpuInfoRequest) Reset() {
	*x = SpuInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpuInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpuInfoRequest) ProtoMessage() {}

func (x *SpuInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpuInfoRequest.ProtoReflect.Descriptor instead.
func (*SpuInfoRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{2}
}

func (x *SpuInfoRequest) GetSpuUuid() string {
	if x != nil {
		return x.SpuUuid
	}
	return ""
}

func (x *SpuInfoRequest) GetExtend() int32 {
	if x != nil {
		return x.Extend
	}
	return 0
}

type SpuInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuInfo       *SpuItem           `protobuf:"bytes,1,opt,name=spu_info,proto3" json:"spu_info,omitempty"`
	SpuSepcDetail *SpuSpecItem       `protobuf:"bytes,2,opt,name=spu_sepc_detail,proto3" json:"spu_sepc_detail,omitempty"`
	SkuList       []*SkuItem         `protobuf:"bytes,3,rep,name=sku_list,proto3" json:"sku_list,omitempty"`
	ActivityData  []*SpuActivityItem `protobuf:"bytes,4,rep,name=activity_data,proto3" json:"activity_data,omitempty"`
}

func (x *SpuInfoReply) Reset() {
	*x = SpuInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpuInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpuInfoReply) ProtoMessage() {}

func (x *SpuInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpuInfoReply.ProtoReflect.Descriptor instead.
func (*SpuInfoReply) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{3}
}

func (x *SpuInfoReply) GetSpuInfo() *SpuItem {
	if x != nil {
		return x.SpuInfo
	}
	return nil
}

func (x *SpuInfoReply) GetSpuSepcDetail() *SpuSpecItem {
	if x != nil {
		return x.SpuSepcDetail
	}
	return nil
}

func (x *SpuInfoReply) GetSkuList() []*SkuItem {
	if x != nil {
		return x.SkuList
	}
	return nil
}

func (x *SpuInfoReply) GetActivityData() []*SpuActivityItem {
	if x != nil {
		return x.ActivityData
	}
	return nil
}

type SpuItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpuItem) Reset() {
	*x = SpuItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpuItem) ProtoMessage() {}

func (x *SpuItem) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpuItem.ProtoReflect.Descriptor instead.
func (*SpuItem) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{4}
}

type SpuSpecItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpuSpecItem) Reset() {
	*x = SpuSpecItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpuSpecItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpuSpecItem) ProtoMessage() {}

func (x *SpuSpecItem) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpuSpecItem.ProtoReflect.Descriptor instead.
func (*SpuSpecItem) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{5}
}

type SpuActivityItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpuActivityItem) Reset() {
	*x = SpuActivityItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpuActivityItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpuActivityItem) ProtoMessage() {}

func (x *SpuActivityItem) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpuActivityItem.ProtoReflect.Descriptor instead.
func (*SpuActivityItem) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{6}
}

type SkuItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuSpecDetail *SkuItem_SkuSpecItem `protobuf:"bytes,1,opt,name=sku_spec_detail,proto3" json:"sku_spec_detail,omitempty"`
}

func (x *SkuItem) Reset() {
	*x = SkuItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuItem) ProtoMessage() {}

func (x *SkuItem) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuItem.ProtoReflect.Descriptor instead.
func (*SkuItem) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{7}
}

func (x *SkuItem) GetSkuSpecDetail() *SkuItem_SkuSpecItem {
	if x != nil {
		return x.SkuSpecDetail
	}
	return nil
}

//BatchSpuInfo
type BatchSpuInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuUuids []string `protobuf:"bytes,1,rep,name=spu_uuids,proto3" json:"spu_uuids,omitempty"`
}

func (x *BatchSpuInfoRequest) Reset() {
	*x = BatchSpuInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchSpuInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSpuInfoRequest) ProtoMessage() {}

func (x *BatchSpuInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSpuInfoRequest.ProtoReflect.Descriptor instead.
func (*BatchSpuInfoRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{8}
}

func (x *BatchSpuInfoRequest) GetSpuUuids() []string {
	if x != nil {
		return x.SpuUuids
	}
	return nil
}

type BatchSpuInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BatchSpuInfoReply) Reset() {
	*x = BatchSpuInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchSpuInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSpuInfoReply) ProtoMessage() {}

func (x *BatchSpuInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSpuInfoReply.ProtoReflect.Descriptor instead.
func (*BatchSpuInfoReply) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{9}
}

// SkuInfo
type SkuInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuUuid string `protobuf:"bytes,1,opt,name=sku_uuid,proto3" json:"sku_uuid,omitempty"`
}

func (x *SkuInfoRequest) Reset() {
	*x = SkuInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuInfoRequest) ProtoMessage() {}

func (x *SkuInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuInfoRequest.ProtoReflect.Descriptor instead.
func (*SkuInfoRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{10}
}

func (x *SkuInfoRequest) GetSkuUuid() string {
	if x != nil {
		return x.SkuUuid
	}
	return ""
}

type SkuInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SkuInfoReply) Reset() {
	*x = SkuInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuInfoReply) ProtoMessage() {}

func (x *SkuInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuInfoReply.ProtoReflect.Descriptor instead.
func (*SkuInfoReply) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{11}
}

// BatchSkuInfo
type BatchSkuInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuUuids []string `protobuf:"bytes,1,rep,name=sku_uuids,proto3" json:"sku_uuids,omitempty"`
}

func (x *BatchSkuInfoRequest) Reset() {
	*x = BatchSkuInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchSkuInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSkuInfoRequest) ProtoMessage() {}

func (x *BatchSkuInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSkuInfoRequest.ProtoReflect.Descriptor instead.
func (*BatchSkuInfoRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{12}
}

func (x *BatchSkuInfoRequest) GetSkuUuids() []string {
	if x != nil {
		return x.SkuUuids
	}
	return nil
}

type BatchSkuInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BatchSkuInfoReply) Reset() {
	*x = BatchSkuInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchSkuInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSkuInfoReply) ProtoMessage() {}

func (x *BatchSkuInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSkuInfoReply.ProtoReflect.Descriptor instead.
func (*BatchSkuInfoReply) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{13}
}

// SpuAcitvityInfo
type SpuAcitvityInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpuAcitvityInfoRequest) Reset() {
	*x = SpuAcitvityInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpuAcitvityInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpuAcitvityInfoRequest) ProtoMessage() {}

func (x *SpuAcitvityInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpuAcitvityInfoRequest.ProtoReflect.Descriptor instead.
func (*SpuAcitvityInfoRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{14}
}

type SpuAcitvityInfoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SpuAcitvityInfoReply) Reset() {
	*x = SpuAcitvityInfoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpuAcitvityInfoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpuAcitvityInfoReply) ProtoMessage() {}

func (x *SpuAcitvityInfoReply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpuAcitvityInfoReply.ProtoReflect.Descriptor instead.
func (*SpuAcitvityInfoReply) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{15}
}

type SkuItem_SkuSpecItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SkuItem_SkuSpecItem) Reset() {
	*x = SkuItem_SkuSpecItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_v1_goods_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkuItem_SkuSpecItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuItem_SkuSpecItem) ProtoMessage() {}

func (x *SkuItem_SkuSpecItem) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_goods_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuItem_SkuSpecItem.ProtoReflect.Descriptor instead.
func (*SkuItem_SkuSpecItem) Descriptor() ([]byte, []int) {
	return file_demo_v1_goods_proto_rawDescGZIP(), []int{7, 0}
}

var File_demo_v1_goods_proto protoreflect.FileDescriptor

var file_demo_v1_goods_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x4c, 0x0a, 0x0e, 0x53, 0x70, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x1a, 0x02, 0x28, 0x00, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x1d, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x09, 0xfa,
	0x42, 0x06, 0x1a, 0x04, 0x18, 0x32, 0x28, 0x0a, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x0e,
	0x0a, 0x0c, 0x53, 0x70, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x5a,
	0x0a, 0x0e, 0x53, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x25, 0x0a, 0x08, 0x73, 0x70, 0x75, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x72, 0x04, 0x10, 0x18, 0x18, 0x18, 0x52, 0x08, 0x73,
	0x70, 0x75, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x06, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x1a, 0x04, 0x30, 0x00,
	0x30, 0x01, 0x52, 0x06, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x22, 0xd6, 0x01, 0x0a, 0x0c, 0x53,
	0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x08, 0x73,
	0x70, 0x75, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x70, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x73, 0x70, 0x75, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x12, 0x39, 0x0a, 0x0f, 0x73, 0x70, 0x75, 0x5f, 0x73, 0x65, 0x70, 0x63,
	0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x70, 0x75, 0x53, 0x70, 0x65, 0x63, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0f,
	0x73, 0x70, 0x75, 0x5f, 0x73, 0x65, 0x70, 0x63, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12,
	0x27, 0x0a, 0x08, 0x73, 0x6b, 0x75, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6b, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08,
	0x73, 0x6b, 0x75, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x75, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x09, 0x0a, 0x07, 0x53, 0x70, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x0d,
	0x0a, 0x0b, 0x53, 0x70, 0x75, 0x53, 0x70, 0x65, 0x63, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x11, 0x0a,
	0x0f, 0x53, 0x70, 0x75, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x74, 0x65, 0x6d,
	0x22, 0x5b, 0x0a, 0x07, 0x53, 0x6b, 0x75, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x41, 0x0a, 0x0f, 0x73,
	0x6b, 0x75, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6b, 0x75, 0x49, 0x74, 0x65,
	0x6d, 0x2e, 0x53, 0x6b, 0x75, 0x53, 0x70, 0x65, 0x63, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0f, 0x73,
	0x6b, 0x75, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x1a, 0x0d,
	0x0a, 0x0b, 0x53, 0x6b, 0x75, 0x53, 0x70, 0x65, 0x63, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x3f, 0x0a,
	0x13, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x09, 0x73, 0x70, 0x75, 0x5f, 0x75, 0x75, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x92, 0x01, 0x04, 0x08,
	0x01, 0x10, 0x32, 0x52, 0x09, 0x73, 0x70, 0x75, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x73, 0x22, 0x13,
	0x0a, 0x11, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x37, 0x0a, 0x0e, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x73, 0x6b, 0x75, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x72, 0x04, 0x10, 0x18,
	0x18, 0x18, 0x52, 0x08, 0x73, 0x6b, 0x75, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x22, 0x0e, 0x0a, 0x0c,
	0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x3f, 0x0a, 0x13,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x09, 0x73, 0x6b, 0x75, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x92, 0x01, 0x04, 0x08, 0x18,
	0x10, 0x18, 0x52, 0x09, 0x73, 0x6b, 0x75, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x73, 0x22, 0x13, 0x0a,
	0x11, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x70, 0x75, 0x41, 0x63, 0x69, 0x74, 0x76, 0x69, 0x74,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14,
	0x53, 0x70, 0x75, 0x41, 0x63, 0x69, 0x74, 0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x32, 0xe0, 0x04, 0x0a, 0x0c, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x07, 0x53, 0x70, 0x75, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x75, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x3a, 0x01,
	0x2a, 0x22, 0x19, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x2f, 0x73, 0x70, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x55, 0x0a, 0x07,
	0x53, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x75,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x24, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x3a, 0x01, 0x2a, 0x22, 0x19, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2f, 0x73, 0x70, 0x75, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x69, 0x0a, 0x0c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x70, 0x75, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x17, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x70,
	0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x76,
	0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x29, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x23, 0x3a, 0x01, 0x2a, 0x22, 0x1e,
	0x2f, 0x73, 0x68, 0x6f, 0x70, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x2f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x53, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x55,
	0x0a, 0x07, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x3a, 0x01, 0x2a, 0x22, 0x19, 0x2f, 0x73, 0x68, 0x6f,
	0x70, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2f, 0x73, 0x6b,
	0x75, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x69, 0x0a, 0x0c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x6b,
	0x75, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x29, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x23, 0x3a, 0x01, 0x2a,
	0x22, 0x1e, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x2f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x75, 0x0a, 0x0f, 0x53, 0x70, 0x75, 0x41, 0x63, 0x69, 0x74, 0x76, 0x69, 0x74, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x75, 0x41, 0x63, 0x69, 0x74,
	0x76, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x75, 0x41, 0x63, 0x69, 0x74, 0x76, 0x69, 0x74, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2c, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x26, 0x3a, 0x01, 0x2a, 0x22, 0x21, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x32, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2f, 0x73, 0x70, 0x75, 0x41, 0x63, 0x69, 0x74, 0x76,
	0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x10, 0x5a, 0x0e, 0x62, 0x65, 0x5f, 0x64, 0x65,
	0x6d, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_demo_v1_goods_proto_rawDescOnce sync.Once
	file_demo_v1_goods_proto_rawDescData = file_demo_v1_goods_proto_rawDesc
)

func file_demo_v1_goods_proto_rawDescGZIP() []byte {
	file_demo_v1_goods_proto_rawDescOnce.Do(func() {
		file_demo_v1_goods_proto_rawDescData = protoimpl.X.CompressGZIP(file_demo_v1_goods_proto_rawDescData)
	})
	return file_demo_v1_goods_proto_rawDescData
}

var file_demo_v1_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_demo_v1_goods_proto_goTypes = []interface{}{
	(*SpuListRequest)(nil),         // 0: v1.SpuListRequest
	(*SpuListReply)(nil),           // 1: v1.SpuListReply
	(*SpuInfoRequest)(nil),         // 2: v1.SpuInfoRequest
	(*SpuInfoReply)(nil),           // 3: v1.SpuInfoReply
	(*SpuItem)(nil),                // 4: v1.SpuItem
	(*SpuSpecItem)(nil),            // 5: v1.SpuSpecItem
	(*SpuActivityItem)(nil),        // 6: v1.SpuActivityItem
	(*SkuItem)(nil),                // 7: v1.SkuItem
	(*BatchSpuInfoRequest)(nil),    // 8: v1.BatchSpuInfoRequest
	(*BatchSpuInfoReply)(nil),      // 9: v1.BatchSpuInfoReply
	(*SkuInfoRequest)(nil),         // 10: v1.SkuInfoRequest
	(*SkuInfoReply)(nil),           // 11: v1.SkuInfoReply
	(*BatchSkuInfoRequest)(nil),    // 12: v1.BatchSkuInfoRequest
	(*BatchSkuInfoReply)(nil),      // 13: v1.BatchSkuInfoReply
	(*SpuAcitvityInfoRequest)(nil), // 14: v1.SpuAcitvityInfoRequest
	(*SpuAcitvityInfoReply)(nil),   // 15: v1.SpuAcitvityInfoReply
	(*SkuItem_SkuSpecItem)(nil),    // 16: v1.SkuItem.SkuSpecItem
}
var file_demo_v1_goods_proto_depIdxs = []int32{
	4,  // 0: v1.SpuInfoReply.spu_info:type_name -> v1.SpuItem
	5,  // 1: v1.SpuInfoReply.spu_sepc_detail:type_name -> v1.SpuSpecItem
	7,  // 2: v1.SpuInfoReply.sku_list:type_name -> v1.SkuItem
	6,  // 3: v1.SpuInfoReply.activity_data:type_name -> v1.SpuActivityItem
	16, // 4: v1.SkuItem.sku_spec_detail:type_name -> v1.SkuItem.SkuSpecItem
	0,  // 5: v1.GoodsService.SpuList:input_type -> v1.SpuListRequest
	2,  // 6: v1.GoodsService.SpuInfo:input_type -> v1.SpuInfoRequest
	8,  // 7: v1.GoodsService.BatchSpuInfo:input_type -> v1.BatchSpuInfoRequest
	10, // 8: v1.GoodsService.SkuInfo:input_type -> v1.SkuInfoRequest
	12, // 9: v1.GoodsService.BatchSkuInfo:input_type -> v1.BatchSkuInfoRequest
	14, // 10: v1.GoodsService.SpuAcitvityInfo:input_type -> v1.SpuAcitvityInfoRequest
	1,  // 11: v1.GoodsService.SpuList:output_type -> v1.SpuListReply
	3,  // 12: v1.GoodsService.SpuInfo:output_type -> v1.SpuInfoReply
	9,  // 13: v1.GoodsService.BatchSpuInfo:output_type -> v1.BatchSpuInfoReply
	11, // 14: v1.GoodsService.SkuInfo:output_type -> v1.SkuInfoReply
	13, // 15: v1.GoodsService.BatchSkuInfo:output_type -> v1.BatchSkuInfoReply
	15, // 16: v1.GoodsService.SpuAcitvityInfo:output_type -> v1.SpuAcitvityInfoReply
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_demo_v1_goods_proto_init() }
func file_demo_v1_goods_proto_init() {
	if File_demo_v1_goods_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_demo_v1_goods_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpuListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_goods_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpuListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_goods_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpuInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_goods_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpuInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_goods_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpuItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_goods_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpuSpecItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_goods_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpuActivityItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_goods_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_goods_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchSpuInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_goods_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchSpuInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_goods_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_goods_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_goods_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchSkuInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_goods_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchSkuInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_goods_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpuAcitvityInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_goods_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpuAcitvityInfoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_v1_goods_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkuItem_SkuSpecItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_demo_v1_goods_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo_v1_goods_proto_goTypes,
		DependencyIndexes: file_demo_v1_goods_proto_depIdxs,
		MessageInfos:      file_demo_v1_goods_proto_msgTypes,
	}.Build()
	File_demo_v1_goods_proto = out.File
	file_demo_v1_goods_proto_rawDesc = nil
	file_demo_v1_goods_proto_goTypes = nil
	file_demo_v1_goods_proto_depIdxs = nil
}
