// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"be_demo/internal/biz/app_biz"
	"be_demo/internal/conf"
	"be_demo/internal/repository/app_repo"
	"be_demo/internal/server/app"
	"be_demo/internal/service/app_serv"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(server *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	greeterRepo := app_repo.NewGreeterRepo(logger)
	greeterUsecase := app_biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := app_serv.NewGreeterService(greeterUsecase)
	grpcServer := app.NewGRPCServer(server, greeterService, logger)
	httpServer := app.NewHTTPServer(server, greeterService, logger)
	kratosApp := newApp(logger, grpcServer, httpServer)
	return kratosApp, func() {
	}, nil
}
