// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.1
// source: conf/nacos.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NacosConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Root *RootWrapper `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
}

func (x *NacosConfig) Reset() {
	*x = NacosConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conf_nacos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NacosConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NacosConfig) ProtoMessage() {}

func (x *NacosConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_nacos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NacosConfig.ProtoReflect.Descriptor instead.
func (*NacosConfig) Descriptor() ([]byte, []int) {
	return file_conf_nacos_proto_rawDescGZIP(), []int{0}
}

func (x *NacosConfig) GetRoot() *RootWrapper {
	if x != nil {
		return x.Root
	}
	return nil
}

type RootWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sign         *Sign         `protobuf:"bytes,1,opt,name=sign,proto3" json:"sign,omitempty"`
	ActivityConf *ActivityConf `protobuf:"bytes,2,opt,name=activity_conf,json=activityConf,proto3" json:"activity_conf,omitempty"`
}

func (x *RootWrapper) Reset() {
	*x = RootWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conf_nacos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RootWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootWrapper) ProtoMessage() {}

func (x *RootWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_conf_nacos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootWrapper.ProtoReflect.Descriptor instead.
func (*RootWrapper) Descriptor() ([]byte, []int) {
	return file_conf_nacos_proto_rawDescGZIP(), []int{1}
}

func (x *RootWrapper) GetSign() *Sign {
	if x != nil {
		return x.Sign
	}
	return nil
}

func (x *RootWrapper) GetActivityConf() *ActivityConf {
	if x != nil {
		return x.ActivityConf
	}
	return nil
}

type Sign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skip bool              `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Keys map[string]string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Sign) Reset() {
	*x = Sign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conf_nacos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sign) ProtoMessage() {}

func (x *Sign) ProtoReflect() protoreflect.Message {
	mi := &file_conf_nacos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sign.ProtoReflect.Descriptor instead.
func (*Sign) Descriptor() ([]byte, []int) {
	return file_conf_nacos_proto_rawDescGZIP(), []int{2}
}

func (x *Sign) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *Sign) GetKeys() map[string]string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type ActivityConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubsidyStartTime  int64                              `protobuf:"varint,1,opt,name=subsidy_start_time,json=subsidyStartTime,proto3" json:"subsidy_start_time,omitempty"`
	SubsidyEndTime    int64                              `protobuf:"varint,2,opt,name=subsidy_end_time,json=subsidyEndTime,proto3" json:"subsidy_end_time,omitempty"`
	DefaultTradeinSpu []int32                            `protobuf:"varint,3,rep,packed,name=default_tradein_spu,json=defaultTradeinSpu,proto3" json:"default_tradein_spu,omitempty"`
	DefaultSubsidy    int64                              `protobuf:"varint,4,opt,name=default_subsidy,json=defaultSubsidy,proto3" json:"default_subsidy,omitempty"`
	PriceMap          map[int64]*ActivityConf_StringList `protobuf:"bytes,5,rep,name=price_map,json=priceMap,proto3" json:"price_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ActivityConf) Reset() {
	*x = ActivityConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conf_nacos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityConf) ProtoMessage() {}

func (x *ActivityConf) ProtoReflect() protoreflect.Message {
	mi := &file_conf_nacos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityConf.ProtoReflect.Descriptor instead.
func (*ActivityConf) Descriptor() ([]byte, []int) {
	return file_conf_nacos_proto_rawDescGZIP(), []int{3}
}

func (x *ActivityConf) GetSubsidyStartTime() int64 {
	if x != nil {
		return x.SubsidyStartTime
	}
	return 0
}

func (x *ActivityConf) GetSubsidyEndTime() int64 {
	if x != nil {
		return x.SubsidyEndTime
	}
	return 0
}

func (x *ActivityConf) GetDefaultTradeinSpu() []int32 {
	if x != nil {
		return x.DefaultTradeinSpu
	}
	return nil
}

func (x *ActivityConf) GetDefaultSubsidy() int64 {
	if x != nil {
		return x.DefaultSubsidy
	}
	return 0
}

func (x *ActivityConf) GetPriceMap() map[int64]*ActivityConf_StringList {
	if x != nil {
		return x.PriceMap
	}
	return nil
}

type ActivityConf_StringList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []int32 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *ActivityConf_StringList) Reset() {
	*x = ActivityConf_StringList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conf_nacos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityConf_StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityConf_StringList) ProtoMessage() {}

func (x *ActivityConf_StringList) ProtoReflect() protoreflect.Message {
	mi := &file_conf_nacos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityConf_StringList.ProtoReflect.Descriptor instead.
func (*ActivityConf_StringList) Descriptor() ([]byte, []int) {
	return file_conf_nacos_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ActivityConf_StringList) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_conf_nacos_proto protoreflect.FileDescriptor

var file_conf_nacos_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x66, 0x2f, 0x6e, 0x61, 0x63, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x63, 0x6f, 0x6e, 0x66, 0x22, 0x34, 0x0a, 0x0b, 0x4e, 0x61, 0x63, 0x6f,
	0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x25, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x52, 0x6f, 0x6f,
	0x74, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x22, 0x66,
	0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x74, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x1e, 0x0a,
	0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x37, 0x0a,
	0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x22, 0x7d, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x6b,
	0x69, 0x70, 0x12, 0x28, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x2e, 0x4b, 0x65, 0x79,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x1a, 0x37, 0x0a, 0x09,
	0x4b, 0x65, 0x79, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x80, 0x03, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x75, 0x62, 0x73, 0x69, 0x64,
	0x79, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x10, 0x73, 0x75, 0x62, 0x73, 0x69, 0x64, 0x79, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x75, 0x62, 0x73, 0x69, 0x64, 0x79, 0x5f,
	0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e,
	0x73, 0x75, 0x62, 0x73, 0x69, 0x64, 0x79, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2e,
	0x0a, 0x13, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x69,
	0x6e, 0x5f, 0x73, 0x70, 0x75, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x11, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x69, 0x6e, 0x53, 0x70, 0x75, 0x12, 0x27,
	0x0a, 0x0f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x73, 0x69, 0x64,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x53, 0x75, 0x62, 0x73, 0x69, 0x64, 0x79, 0x12, 0x3d, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x5f, 0x6d, 0x61, 0x70, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x2e, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x1a, 0x24, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x5a, 0x0a, 0x0d,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x33, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x43, 0x6f,
	0x6e, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x1c, 0x5a, 0x1a, 0x62, 0x65, 0x5f, 0x64,
	0x65, 0x6d, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x3b, 0x63, 0x6f, 0x6e, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_conf_nacos_proto_rawDescOnce sync.Once
	file_conf_nacos_proto_rawDescData = file_conf_nacos_proto_rawDesc
)

func file_conf_nacos_proto_rawDescGZIP() []byte {
	file_conf_nacos_proto_rawDescOnce.Do(func() {
		file_conf_nacos_proto_rawDescData = protoimpl.X.CompressGZIP(file_conf_nacos_proto_rawDescData)
	})
	return file_conf_nacos_proto_rawDescData
}

var file_conf_nacos_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_conf_nacos_proto_goTypes = []interface{}{
	(*NacosConfig)(nil),             // 0: conf.NacosConfig
	(*RootWrapper)(nil),             // 1: conf.RootWrapper
	(*Sign)(nil),                    // 2: conf.Sign
	(*ActivityConf)(nil),            // 3: conf.ActivityConf
	nil,                             // 4: conf.Sign.KeysEntry
	(*ActivityConf_StringList)(nil), // 5: conf.ActivityConf.StringList
	nil,                             // 6: conf.ActivityConf.PriceMapEntry
}
var file_conf_nacos_proto_depIdxs = []int32{
	1, // 0: conf.NacosConfig.root:type_name -> conf.RootWrapper
	2, // 1: conf.RootWrapper.sign:type_name -> conf.Sign
	3, // 2: conf.RootWrapper.activity_conf:type_name -> conf.ActivityConf
	4, // 3: conf.Sign.keys:type_name -> conf.Sign.KeysEntry
	6, // 4: conf.ActivityConf.price_map:type_name -> conf.ActivityConf.PriceMapEntry
	5, // 5: conf.ActivityConf.PriceMapEntry.value:type_name -> conf.ActivityConf.StringList
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_conf_nacos_proto_init() }
func file_conf_nacos_proto_init() {
	if File_conf_nacos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_conf_nacos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NacosConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conf_nacos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RootWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conf_nacos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conf_nacos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conf_nacos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityConf_StringList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_conf_nacos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_nacos_proto_goTypes,
		DependencyIndexes: file_conf_nacos_proto_depIdxs,
		MessageInfos:      file_conf_nacos_proto_msgTypes,
	}.Build()
	File_conf_nacos_proto = out.File
	file_conf_nacos_proto_rawDesc = nil
	file_conf_nacos_proto_goTypes = nil
	file_conf_nacos_proto_depIdxs = nil
}
