// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"be_demo/internal/biz/cron_biz"
	"be_demo/internal/conf"
	"be_demo/internal/data"
	"be_demo/internal/server/cron"
	"be_demo/internal/service/cron_serv"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	notice := data.NewNotice(bootstrap, logger)
	demoCrontab := cron_biz.NewDemoCrontab(logger, notice)
	demoCronService := cron_serv.NewDemoCronService(logger, demoCrontab)
	server := cron.NewCron(demoCronService)
	app := newApp(logger, server)
	return app, func() {
	}, nil
}
