// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"be_demo/internal/biz/cli_biz"
	"be_demo/internal/conf"
	"be_demo/internal/data"
	"be_demo/internal/server/cli"
	"be_demo/internal/service/cli_serv"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	notice := data.NewNotice(bootstrap, logger)
	demoCliLogic := cli_biz.NewDemoCliLogic(logger, notice)
	demoCmdService := cli_serv.NewDemoCmdService(logger, demoCliLogic)
	server := cli.NewCommandServer(demoCmdService)
	app := newApp(logger, server)
	return app, func() {
	}, nil
}
